#!/bin/sh -*-shell-script-*-

# umask for go-w
umask 022

# core を作成しない
ulimit -c 0

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# 個人の環境変数
if [ "$SHLVL" = 1 -a -f ~/.bash_env ]; then
    . ~/.bash_env
fi

## 入力

# ヒストリ管理
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth
shopt -s histappend cmdhist lithist histverify histreedit

# 補完
shopt -s no_empty_cmd_completion

# 端末サイズをチェックし COLUMNS,LINES を更新
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# 端末に Ecma-48 の色付きが出来るかでカラーかを確認
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    terminal_type=color
fi

# Emacs 内部
if [ "$EMACS" = t ]; then
    terminal_type=simple
fi

## プロンプト
case "$terminal_type" in
    simple)
	PS1='% '
	;;
    color)
	PS1='\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[00;34m\]\w\[\033[00m\]\$ '
	;;
    *)
	PS1='\u@\h:\w\$ '
	;;
esac

# タイトルバーに端末情報を追加
case "$TERM" in
    xterm*|rxvt*) PS1="\[\e]0;\u@\h: \w\a\]$PS1" ;;
esac

# エイリアスを手動作成コマンド
if [ -f ~/.bash_make_aliases ]; then
    alias hh='source ~/.bash_make_aliases ; source ~/.bash_aliases ; unalias hh'
fi

# エイリアスの読み込み
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Completion
if [ -f /etc/bash_completion ]; then
    alias h='source /etc/bash_completion; unalias h'
else
    alias h='echo cannot find /etc/bash_completion; unalias h'
fi

unset terminal_type
