# ~/.bashrc: -*-shell-script-*-
# $Id$

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

PS1="% "

shopt -s checkwinsize

if [ -f ${HOME}/.bash_aliases ]; then
    . ${HOME}/.bash_aliases
fi

if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
