#!/bin/bash
# -*-shell-script-*-

# エイリアスを手動作成コマンド
if [ -f ${HOME}/.bash_make_aliases ]; then
    alias hh='source ~/.bash_make_aliases ; source ~/.bash_aliases ; unalias hh'
fi

# エイリアスの読み込み
if [ -f ${HOME}/.bash_aliases ]; then
    source ${HOME}/.bash_aliases
fi

# タイトルバーに端末情報を追加
case "$TERM" in
xterm*|rxvt*)
        if [ -z "${NO_TERM_PROMPT}" ]; then
            PS1="\[\033]0;\u@\h: \w\007\]$PS1"
        else
            echo -ne "\033]0;${USER}@$(hostname): \w\007"
        fi
        ;;
esac

# Completion
if [ -f "${BASH_COMPLETION}" ]; then
    if [ -n "USE_BASH_COMPLETION" ]; then
        source ${BASH_COMPLETION};
    fi
fi

# for Perl
if [ -n "$PERLBREW_ROOT" -a -n "$PERLBREW_HOME" ]; then

    if [ -n "$PRELOAD_PERLBREW" ]; then
        source ${PERLBREW_ROOT}/etc/bashrc
    else
            if [ -f ${PERLBREW_HOME}/init ]; then
                source ${PERLBREW_HOME}/init
                PATH=${PERLBREW_PATH}:${PATH}
                MANPATH=${PERLBREW_MANPATH}:${MANPATH}
            fi

            function perlbrew() {
                    source ${PERLBREW_ROOT}/etc/bashrc;
                    perlbrew "$@";
            }
    fi
fi

# for PHP
if [ -n "$PHPBREW_ROOT" -a -d "$PHPBREW_ROOT" ]; then

    if [ -f ${PHPBREW_HOME}/init ]; then
        source ${PHPBREW_HOME}/init
        PATH=${PHPBREW_PATH}:${PATH}
    fi

    function phpbrew() {
            source ${PHPBREW_HOME}/bashrc;
            phpbrew "$@";
    }
fi

# for pythonz
if [ -n "${PYTHONZ_ROOT}" -a -d "${PYTHONZ_ROOT}" ]; then

    if [ -n "$PRELOAD_PYTHONZ" ]; then
        source ${PYTHONZ_ROOT}/etc/bashrc
    else

            function pythonz() {
                    source ${PYTHONZ_ROOT}/etc/bashrc;
                    pythonz "$@";
            }
    fi
fi

# for Rbenv
# if [ -n "${RBENV_ROOT}" -a -d "${RBENV_ROOT}" ]; then
#
#     if [ -n "$PRELOAD_REBENV" ]; then
#         eval "$(rbenv init -)"
#     else
#             export PATH="${RBENV_ROOT}/shims:${PATH}"
#             source "$(brew --prefix rbenv)/completions/rbenv.bash"
#     fi
# fi

export VAGRANT_HOME=${VAGRANT_HOME:-/opt/vagrant_home}
#export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

# for composer
export COMPOSER_HOME=${COMPOSER_HOME:-${HOME}/common/composer}
if [ -d "$COMPOSER_HOME" ]; then
    PATH=${PATH}:${COMPOSER_HOME}/vendor/bin
fi

# for GO
export GOPATH=${GOPATH:-/sdk/gocode}
if [ -d "$GOPATH" ]; then
    PATH=${PATH}:${GOPATH}/bin
    #export GOROOT=/usr/local/go
fi

# for NodeJS
if [ -n "${NVM_DIR}" -a -d "${NVM_DIR}" ]; then
    if [ -n "$PRELOAD_NVM" ]; then
        source ${NVM_DIR}/nvm.sh
    else
            function nvm() {
                    source ${NVM_DIR}/nvm.sh
                    nvm "$@";
            }
    fi
fi
