#!/bin/sh -*-shell-script-*-
# $Id: bash_profile 187 2009-02-11 05:14:31Z shoichi $

# if running bash
if [ -n "$BASH_VERSION" ]; then
        # include .bashrc if it exists
        if [ -f "$HOME/.bashrc" ]; then
                . "$HOME/.bashrc"
        fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/common/bin" ] ; then
        PATH="$HOME/common/bin:$PATH"
fi

if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
fi
