#!/bin/sh
# -*-shell-script-*-

sysname=$(uname -s)
machine=$(uname -m)

if [ -n "$COMSPEC" ]; then
        sysname=Windows
fi

case $sysname in
Linux)
        # for Debian GNU/Linux
        if [ -e /etc/debian_version ]; then
                export DEBFULLNAME='Shoichi Fukusaka'
                export DEBEMAIL='fukusaka@xa2.so-net.ne.jp'
        fi
        ;;
Darwin)
        export EDITOR=/usr/bin/vim

        # Prefer to Use Homebrew
        if [ "$machine" = "arm64" ]; then
                homebrew_dir=/opt/homebrew
        else
                homebrew_dir=/usr/local
        fi

        if [ -x "$homebrew_dir/bin/brew" ]; then
                PATH="$homebrew_dir/bin:$homebrew_dir/sbin${PATH+:$PATH}";
                MANPATH="$homebrew_dir/share/man${MANPATH+:$MANPATH}";
                #INFOPATH="$homebrew_dir/share/info:${INFOPATH:-}";

                export HOMEBREW_PREFIX="$homebrew_dir"

                BASH_COMPLETION="$homebrew_dir/etc/bash_completion"
                if [ -x "$homebrew_dir/bin/vimpager" ]; then
                        export PAGER="$homebrew_dir/bin/vimpager"
                fi
        fi

        unset homebrew_dir
        ;;
SunOS)
        PATH=/usr/bin:/usr/sbin
        PATH=$PATH:/usr/sfw/bin
        PATH=$PATH:/usr/ccs/bin:/usr/ucb

        MANPATH=/usr/share/man
        MANPATH=$MANPATH:/usr/sfw/share/man

        # Freeware for Solars from Sunfreewave.com
        PATH=/usr/local/bin:$PATH
        MANPATH=/usr/local/share/man:$MANPATH

        #[ "$TERM" = xterm-color ] && TERM=xterm
        export TERMINFO=$HOME/.terminfo

        # pager
        export PAGER=/usr/bin/less
        ;;
Windows)
        #export LANG=ja_JP.SJIS
        #Cygwin 1.7以降 UTF-8がサポートされている
        #export LANG=ja_JP.UTF-8
        ;;
esac
unset sysname
unset machine

export PATH MANPATH
