#!/bin/sh

if [ -f "${HOME}/.bash_profile" ]; then . "${HOME}/.bash_profile"; fi


# X環境での設定
export XMODIFIERS='@im=kinput2'

xset +fp ${HOME}/lib/fonts:unscaled
xset fp rehash

xrdb .Xresources  > /dev/null 2>&1
xhost +local: > /dev/null 2>&1
kinput2 -canna -cannafile ~/.canna > /dev/null 2>&1 &

xset b off
#xset m 2 5

exec afterstep > /dev/null 2>&1
#exec olwm
#exec fvwm2
#exec wmaker
