# ~/.bash_profile
# $Id$

if [ -f ${HOME}/.bashrc ]; then . ${HOME}/.bashrc; fi

. ${HOME}/.default/sh

#
for i in ${SHCONFDIR}/profile.d/*.sh; do
    if [ -x $i ]; then
	. $i ${CONFDOMAIN}
    fi
done
unset i

# Local Variables:
# mode: shell-script
# End:
