# ~/.bashrc
# $Id$

# 対話シェルで無ければ、以後実行しない。
[ -z "$PS1" ] && return

. ${HOME}/.default/sh

#
if [ -f ${SHCONFDIR}/bashrc.${CONFDOMAIN}.sh ]; then
    . ${SHCONFDIR}/bashrc.${CONFDOMAIN}.sh
else
    . ${SHCONFDIR}/bashrc.default.sh
fi

# Local Variables:
# mode: shell-script
# End:
