\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename @INFONAME
@settitle @FNAME
@c %**end of header

@c Copyright (C) @@YEAR@@ @@NAME@@
@c
@c Author: @@NAME@@ <@@ADDRESS@@>
@c Maintainer: @@NAME@@ <@@ADDRESS@@>
@c Created: @@DATE@@
@c Version: 1.0
@c Keywords:

@c This file is part of

@@LICENSE@@

@ifinfo
This file documents ...
Permission is granted to ...
@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage
@title NAME-OF-MANUAL-WHEN-PRINTED
@subtitle SUBTITLE-IF-ANY
@subtitle SECOND-SUBTITLE
@author AUTHOR

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} YEAR COPYRIGHT-OWNER

Published by ...

Permission is granted to ...
@end titlepage

@node Top, Overview, , (dir)

@ifinfo
This document describes ...

This document applies to version ...
of the program named ...
@end ifinfo

@menu
@end menu

@node    First Chapter, Second Chapter, top,      top
@comment node-name,     next,           previous, up
@chapter First Chapter
@cindex Index entry for First Chapter



@contents
@bye

@@@@
FNAME: (file-name-nondirectory buffer-file-name)
NAME: programmer-name
ADDRESS: programmer-mail-address
YEAR: (format-time-string "%Y")
DATE: (format-time-string "%d %b %Y")
LICENSE: (my-license-string 'GPL "@c " t)
@@@@
