- hosts: localhost
  connection: local
  become: no

  tasks:
     - name: unbound config file
       copy: src=files/unbound-real.conf dest=/usr/local/etc/unbound/unbound.conf
       notify: restart unbound
     - name: setup unbound
       script: files/setup-unbound.sh

     - name: nsd config file
       copy: src=files/nsd-real.conf dest=/usr/local/etc/nsd/nsd-real.conf
       notify: restart nsd
     - name: nsd launch plist
       copy: src=files/homebrew.mxcl.nsd.plist dest=/usr/local/etc/nsd/homebrew.mxcl.nsd.plist
       notify: restart nsd
     - name: setup nsd
       script: files/setup-nsd.sh

     - name: setup ngix
       script: files/setup-nginx.sh

  handlers:
   - name: restart unbound
     sudo: yes
     command: unbound-control reload
   - name: restart nsd
     sudo: yes
     command: nsd-control reload
