- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  roles:
    - homebrew
    - homebrew-cask

  vars:
    homebrew_repositories:
      - homebrew/binary
      - homebrew/dupes
      - homebrew/versions

    homebrew_packages:
      - ansible
      - readline
      - openssl
      - autoconf-archive
      - automake
      - bash-completion
      - cmake
      - ctags
      - curl
      - d-bus
      - flow
      - git
      - glib
      - gnutls
      - go
      - graphviz
      - icu4c
      - imagemagick
      - jq
      - lha
      - librsvg
      - lv
      - mailutils
      - nginx
      - nkf
      - node
      - nsd
      - nvm
      - peco
      - pidof
      - pkg-config
      - python
      - reattach-to-user-namespace
      - redis
      - shellcheck
      - sqlite
      - tmux
      - tofrodos
      - tree
      - unbound
      - unrar
      - wget
      - xz
      - { name: emacs, install_options: with-cocoa,with-gnutls,with-ctags,with-librsvg }

    homebrew_cask_repositories:
      - caskroom/cask
      - caskroom/versions

    homebrew_cask_packages:
      - firefox
      - google-chrome
      - mysqlworkbench
      - sourcetree
      - sqlitestudio
      - vagrant
      - vagrant-manager
      - virtualbox
      - xquartz
      - docker
      - kitematic
      - tower
      - java6
      - java7
      - java
      - appcode
      - reveal
      - android-studio
      - omnifocus
      - omnioutliner
      - omnigraffle
      - omnipresence
      - omniplan
      - 1password
      - microsoft-office
      - intellij-idea
      - datagrip
      - vmware-fusion
      - apache-directory-studio
      - appcleaner
      - astah-professional
      - coda
      - evernote
      - sequel-pro
      - skype
      - sublime-text
      - kindle
      - dropbox
      - cornerstone
      - google-drive
      - rstudio
      - handbrake
      - karabiner
      - grandperspective
      - slack
      - unity
      - googleappengine
      - transmission
      - android-file-transfer
      - adobe-creative-cloud
      - diskwave
      - owasp-zap
      - pgadmin3
      - mactex
      - realm-browser

  tasks:
     - name: unbound config file
       copy: src=files/unbound-real.conf dest=/usr/local/etc/unbound/unbound.conf
       notify: restart unbound
     - name: setup unbound
       script: files/setup-unbound.sh

     - name: nsd config file
       copy: src=files/nsd-real.conf dest=/usr/local/etc/nsd/nsd-real.conf
       notify: restart nsd
     - name: nsd launch plist
       copy: src=files/homebrew.mxcl.nsd.plist dest=/usr/local/etc/nsd/homebrew.mxcl.nsd.plist
       notify: restart nsd
     - name: setup nsd
       script: files/setup-nsd.sh

     - name: setup ngix
       script: files/setup-nginx.sh

  handlers:
   - name: restart unbound
     sudo: yes
     command: unbound-control reload
   - name: restart nsd
     sudo: yes
     command: nsd-control reload
