- hosts: localhost
  connection: local
  become: no

  roles:
    - role: homebrew
      tags: [ 'common' ]
      homebrew_repositories:
        - homebrew/binary
        - homebrew/dupes
        - homebrew/versions
      homebrew_packages:
        - ansible
        - bash-completion
        - ctags
        - curl
        - d-bus
        - doxygen
        - git
        - git-flow
        - git-lfs
        - glib
        - gnutls
        - go
        - graphviz
        - icu4c
        - imagemagick
        - imagemagick@6
        - jq
        - lha
        - librsvg
        - lv
        - mailutils
        - nginx
        - nsd
        - openssl
        - pidof
        - pkg-config
        - readline
        - reattach-to-user-namespace
        - tmux
        - tree
        - unbound
        - unrar
        - wget
        - xz
        - name: emacs
          install_options:
           - with-cocoa
           - with-gnutls
           - with-librsvg
           - with-imagemagick
    - role: homebrew
      tags: [ 'extra' ]
      homebrew_packages:
        - tofrodos
        - nkf
        - peco
        - hugo
    - role: homebrew
      tags: [ 'develop' ]
      homebrew_packages:
        - autoconf-archive
        - automake
        - awscli
        - cmake
        - flow
        - node
        - nvm
        - python
        - redis
        - shellcheck
        - sqlite
        - postgresql
        - tinycdb
        - rbenv
        - nsd
        - pandoc
        - pandoc-crossref
        - wakeonlan
    - role: homebrew
      tags: [ 'develop-extra' ]
      homebrew_packages:
        - boost
        - libxml2
        - gtk+
        - gtkmm
        - ucommon
