#cloud-config

groups:
  - docker

package_update: true

packages:
  - ca-certificates
  - curl

runcmd:
  # install Docker CE
  - |
    export DEBIAN_FRONTEND=noninteractive
    curl -fsSL https://get.docker.com | sh
  - adduser ubuntu docker

snap:
  commands:
    - [install, multipass-sshfs]
